@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package com.fredhappyface.anothergemsmod.blocks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;